// Code generated by RedSock CLI.
// DO EDIT, DON'T DELETE THIS FILE.

package app

type Custom struct{}

func (c *Custom) Init(a *App) error {
	// Repository, Service logic, transport registration happens here
	return nil
}
