package projpatterns

import (
	_ "embed"
	"reflect"
	"strings"
	"text/template"

	errors "github.com/Red-Sock/trace-errors"
	"github.com/godverv/matreshka"

	"github.com/Red-Sock/rscli/internal/rw"
	"github.com/Red-Sock/rscli/internal/utils/cases"
)

//go:embed pattern_c/internal/config/config_struct.go.pattern
var structPattern string

//go:embed pattern_c/internal/clients/grpc/grpc_client.go.pattern
var grpcConnectionPattern string

var (
	configStructTemplate   *template.Template
	grpcConnectionTemplate *template.Template
)

func init() {
	configStructTemplate = template.Must(
		template.New("environment").
			Parse(structPattern))

	grpcConnectionTemplate = template.Must(
		template.New("grpc_connection").
			Parse(grpcConnectionPattern))
}

type KeyValue struct {
	Key   string
	Value string
}

type structArgs struct {
	GenTag string

	StructName string
	Imports    map[string]string // path to alias
	Fields     []KeyValue
}

func newECG(structName string) structArgs {
	return structArgs{
		GenTag:     "// Code generated by RedSock CLI. DO NOT EDIT.",
		StructName: structName,
		Imports:    map[string]string{},
		Fields:     nil,
	}
}

func GenerateEnvironmentConfigStruct(environment matreshka.Environment) ([]byte, error) {
	ecg := newECG("EnvironmentConfig")

	nameReplacer := strings.NewReplacer(
		" ", "_",
		"-", "_")

	normalizeName := func(s string) string {
		s = nameReplacer.Replace(s)
		s = cases.SnakeToPascal(s)
		return s
	}

	for _, env := range environment {
		var fieldKV KeyValue
		fieldKV.Key = normalizeName(env.Name)

		refVal := reflect.ValueOf(env.Value)
		tp := refVal.Type()

		fieldKV.Value = tp.String()

		if tp.PkgPath() != "" {
			ecg.Imports[tp.PkgPath()] = "" // todo think about aliases?
		}

		ecg.Fields = append(ecg.Fields, fieldKV)

	}

	buf := &rw.RW{}
	err := configStructTemplate.Execute(buf, ecg)
	if err != nil {
		return nil, errors.Wrap(err, "error executing template")
	}

	return buf.Bytes(), nil
}

func GenerateDataSourcesConfigStruct(dataSources matreshka.DataSources) ([]byte, error) {
	ecg := newECG("DataSourcesConfig")

	nameReplacer := strings.NewReplacer(
		" ", "_",
		"-", "_")

	normalizeName := func(s string) string {
		s = nameReplacer.Replace(s)
		s = cases.SnakeToPascal(s)
		return s
	}

	for _, ds := range dataSources {
		var fieldKV KeyValue
		fieldKV.Key = normalizeName(ds.GetName())

		refVal := reflect.ValueOf(ds)
		tp := refVal.Type()

		fieldKV.Value = tp.String()

		kind := tp.Kind()
		if kind == reflect.Ptr {
			tp = tp.Elem()
		}

		if tp.PkgPath() != "" {
			ecg.Imports[tp.PkgPath()] = "" // todo think about aliases?
		}

		ecg.Fields = append(ecg.Fields, fieldKV)

	}

	buf := &rw.RW{}
	err := configStructTemplate.Execute(buf, ecg)
	if err != nil {
		return nil, errors.Wrap(err, "error executing template")
	}

	return buf.Bytes(), nil
}

type GrpcClientArgs struct {
	ApiPackage  string
	Constructor string
	ClientName  string
}

func GenerateGRPCClient(args GrpcClientArgs) ([]byte, error) {
	buf := &rw.RW{}
	err := grpcConnectionTemplate.Execute(buf, args)
	if err != nil {
		return nil, errors.Wrap(err, "error executing template")
	}

	return buf.Bytes(), nil
}
