PROJECT_NAME=proj_name
PROJECT_PATH=abs_proj_path
PATH_TO_MAIN_GO=path_to_main

.PHONY: build-app
build-app:
	cd $(PROJECT_PATH) && go build -o $(PWD)/$(PROJECT_NAME) $(PROJECT_PATH)/$(PATH_TO_MAIN_GO)/main.go


.PHONY: env-up
env-up:
	# TODO

.PHONY: env-down
env-down:
	# TODO

