PROJECT_NAME=proj_name
PROJECT_PATH=abs_proj_path

.PHONY: build-app
build-app:
	cd $(PROJECT_PATH) && go build -o $(PWD)/$(PROJECT_NAME) $(PROJECT_PATH)/main.go


.PHONY: env-up
env-up:
	# TODO

.PHONY: env-down
env-down:
	# TODO

