app_info:
  name: test_project
  version: v0.0.1
  startup_duration: 10s
servers:
  80:
    /{GRPC}:
      module: github.com/Test_AddDependency/grpc
      gateway: /api
environment:
  - name: log_level
    enum: [Trace, Debug, Info, Warn, Error, Fatal, Panic]
    type: string
    value: Info
  - name: log_format
    enum: [JSON,TEXT]
    type: string
    value: TEXT
