// Code generated by RedSock CLI. DO NOT EDIT.

package app

import (
	"Test_AddDependency/REDIS/internal/clients/redis"
	errors "github.com/Red-Sock/trace-errors"
)

func (a *App) InitDataSources() (err error) {
	a.Redis, err = redis.New(a.Cfg.DataSources.Redis)
	if err != nil {
		return errors.Wrap(err, "error during redis connection initialization")
	}

	return nil
}
