// Code generated by rscli. DO NOT EDIT.

package telegram

import (
	"github.com/Red-Sock/go_tg/client"
	"github.com/godverv/matreshka/resources"
)

func New(cfg *resources.Telegram) *client.Bot {
	return client.NewBot(cfg.ApiKey)
}
