// Code generated by RedSock CLI. DO NOT EDIT.

package app

import (
	"Test_AddDependency/POSTGRES/internal/clients/sqldb"
	errors "github.com/Red-Sock/trace-errors"
)

func (a *App) InitDataSources() (err error) {
	a.Postgres, err = sqldb.New(a.Cfg.DataSources.Postgres)
	if err != nil {
		return errors.Wrap(err, "error during sql connection initialization")
	}

	return nil
}
