// Code generated by rscli. DO NOT EDIT.

package redis

import (
	"github.com/go-redis/redis"
	"github.com/pkg/errors"

	"financial-microservice/internal/utils/closer"
)

var ErrUnexpectedPing = errors.New("error pinging redis")

func New(opts *redis.Options) (*redis.Client, error) {
	c := redis.NewClient(opts)

	res, err := c.Ping().Result()
	if err != nil {
		return nil, errors.Wrap(err, "error checking connection to redis")
	}

	if res != "pong" {
		return nil, errors.Wrapf(ErrUnexpectedPing, "not a pong has returned but %s", res)
	}

	closer.Add(c.Close)

	return c, nil
}
