// Code generated by rscli. DO NOT EDIT.

package tg

import (
	"github.com/Red-Sock/go_tg/client"

	"financial-microservice/internal/config"
)

func New(cfg *config.Config) *client.Bot {
	return client.NewBot(cfg.GetString(config.ServerTgApikey))
}
