app_info:
    name: test_project
    version: v0.0.1
    startup_duration: 10s
data_sources:
    - resource_name: redis
      host: localhost
      port: 6379
      user: ""
      pwd: ""
      db: 0
environment:
    - enum:
          - Trace
          - Debug
          - Info
          - Warn
          - Error
          - Fatal
          - Panic
      name: log_level
      type: string
      value: Info
    - enum:
          - JSON
          - TEXT
      name: log_format
      type: string
      value: TEXT