env:
  path_to_main: 'cmd/proj_name/main.go'
  path_to_config: 'config/dev.yaml'
  paths_to_clients:
    - internal/clients
  path_to_servers:
    - internal/transport
  path_to_migrations: 'migrations'
default_project_git_path: github.com/Red-Sock