app_info:
    name: test_project
    version: v0.0.1
    startup_duration: 10s
data_sources:
    - resource_name: postgres
      migrations_folder: ./migrations
      host: localhost
      port: 5432
      user: postgres
      pwd: ""
      name: postgres
      ssl_mode: ""
environment:
    - enum:
          - Trace
          - Debug
          - Info
          - Warn
          - Error
          - Fatal
          - Panic
      name: log_level
      type: string
      value: Info
    - enum:
          - JSON
          - TEXT
      name: log_format
      type: string
      value: TEXT