// Code generated by RedSock CLI. DO NOT EDIT.

package postgres

import (
	"context"
	"fmt"

	"github.com/Red-Sock/toolbox/closer"
	"github.com/Red-Sock/trace-errors"
	"github.com/godverv/matreshka/resources"
	"github.com/jackc/pgx/v5"
	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"
	"github.com/sirupsen/logrus"
)

func New(ctx context.Context, cfg *resources.Postgres) (TxManager, error) {
	conbStr := createConnectionString(cfg)

	conn, err := pgx.Connect(ctx, conbStr)
	if err != nil {
		return nil, errors.Wrap(err, "error checking connection to postgres")
	}

	closer.Add(func() error {
		return conn.Close(ctx)
	})

	err = checkMigrate(conbStr)
	if err != nil {
		return nil, errors.Wrap(err, "error checking migrations")
	}

	return &tx{Conn: conn}, nil
}

func createConnectionString(cfg *resources.Postgres) string {
	return fmt.Sprintf("postgresql://%s:%s@%s:%s/%s",
		cfg.User,
		cfg.Pwd,
		cfg.Host,
		cfg.Port,
		cfg.DbName,
	)
}

func checkMigrate(connString string) error {
	conn, err := goose.OpenDBWithDriver("pgx", connString)
	if err != nil {
		return errors.Wrap(err, "error opening pg db connection")
	}

	goose.SetLogger(logrus.StandardLogger())

	err = goose.Up(conn, "./migrations")
	if err != nil {
		return errors.Wrap(err, "error performing up")
	}

	return nil
}
