package config_generators

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"go.verv.tech/matreshka"
)

func Test_GenerateEnvConfig(t *testing.T) {
	t.Run("environment", func(t *testing.T) {
		env := matreshka.Environment{
			{
				Name:  "one",
				Type:  "int",
				Value: 1,
			},
			{
				Name:  "two",
				Type:  "duration",
				Value: time.Second,
			},
		}

		_, generatedFolder, err := newGenerateEnvironmentConfigStruct(env)()
		require.NoError(t, err)

		expected := `
// Code generated by RedSock CLI. DO NOT EDIT.

package config

import ( 
     "time"
)

type EnvironmentConfig struct { 
    One int
    Two time.Duration
}
`[1:]
		require.Equal(t, expected, string(generatedFolder.Content))
	})
}
