package config_generators

import (
	_ "embed"
	"text/template"
)

const defaultGenTag = "// Code generated by RedSock CLI. DO NOT EDIT."

var (

	//go:embed templates/autoload.go.pattern
	configAutoLoadPattern  string
	configAutoLoadTemplate *template.Template

	//go:embed templates/config_struct.go.pattern
	configStructPattern  string
	configStructTemplate *template.Template

	//go:embed templates/grpc_client.go.pattern
	grpcConnectionPattern  string
	grpcConnectionTemplate *template.Template
)

func init() {
	configAutoLoadTemplate = template.Must(
		template.New("config_autoload").
			Parse(configAutoLoadPattern))

	configStructTemplate = template.Must(
		template.New("environment").
			Parse(configStructPattern))

	grpcConnectionTemplate = template.Must(
		template.New("grpc_connection").
			Parse(grpcConnectionPattern))

}
