// Code generated by RedSock CLI. DO NOT EDIT.

package grpc

import (
	"context"

	errors "github.com/Red-Sock/trace-errors"
	"github.com/godverv/matreshka/resources"
	"google.golang.org/grpc"
)

// TODO вынесено в отдельную функцию. Мб потом через connCfg можно будет нахуевертить опции соединения
func connect(ctx context.Context, connCfg *resources.GRPC) (*grpc.ClientConn, error) {
	dial, err := grpc.DialContext(ctx, connCfg.ConnectionString)
	if err != nil {
		return nil, errors.Wrap(err, "error dialing")
	}

	return dial, nil
}
