name: branch-push
run-name: ${{ github.REF_NAME }}
on:
  push:
    branches:
      - RSI-*

jobs:
  main-create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Check if PR exists
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list \
              --repo "$GITHUB_REPOSITORY" \
              --json baseRefName,headRefName \
              --jq '
                  map(select(.baseRefName == "main" and .headRefName == "${{ github.ref }}"))
                  | length
              ')
          
          echo "skip=true" >> "$GITHUB_OUTPUT"
          
          if ((prs > 0)); then
              echo "skip=true" >> "$GITHUB_OUTPUT"
          fi
      - name: echo prev step
        run: echo ${{ steps.check.outputs.skip }}
      - name: Pull request creation
        if: '!steps.check.outputs.skip'
        run: >
          gh pr create
          -B main
          -H ${{ github.REF }}
          --title 'RELEASE OF ${{ github.REF }}'
          --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}