name: branch-push
run-name: ${{ github.REF_NAME }}
on:
  push:
    branches:
      - RSI-*

jobs:
  main-create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Check weather PR exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list \
              --repo "$GITHUB_REPOSITORY" \
              --json baseRefName,headRefName \
              --jq '
                  map(select(.baseRefName == "master" and .headRefName == "dev"))
                  | length
              ')
          
          if ((prs > 0)); then
              echo "skip=true" >> "$GITHUB_OUTPUT"
          fi


      - name: Pull request creation
        run: |
          response=$(gh pr create \
          -B main \
          -H ${{ github.REF }} \
          --title 'RELEASE OF ${{ github.REF }}' \
          --body 'Created by Github action')
          
          echo $(response)

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}