name: branch-push
run-name: ${{ github.REF_NAME }} pull request
on:
  push:
    branches:
      - RSI-*

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: CreatePR
        uses: RedSockActions/create_pr@v0.0.1
