name: branch-push
run-name: ${{ github.REF_NAME }}
on:
  push:
    branches:
      - RSI-*

jobs:
  main-create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: pull-request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '${{ github.ref_name }}',
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'main',
              body: [
                'Release for ',
                '[${{ github.ref_name }}](https://redsock.youtrack.cloud/issue/${{ github.ref_name }}).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['feature', 'automated pr']
            });