name: branch-push
run-name: ${{ github.REF_NAME }}
on:
  push:
    branches:
      - RSI-*

jobs:
  main-create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
        run: gh pr create -B main -H ${{ github.REF }} --title 'RELEASE OF ${{ github.REF }}' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}