name: branch-push
run-name: ${{ github.REF_NAME }} pull request
on:
  push:
    branches:
      - RSI-*

jobs:
  main-create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Check if PR exists
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list \
              --repo "$GITHUB_REPOSITORY" \
              --json baseRefName,headRefName \
              --jq '
                  map(select(.baseRefName == "${{ github.base_ref }}" and .headRefName == "${{ github.REF_NAME }}"))
                  | length
              ')
          if ((prs = 0)); then
              gh pr create \
                -B main \
                -H ${{ github.REF }} \
                --title 'RELEASE OF ${{ github.REF }}' \
                --body 'Created by Github action'
          fi
