name: branch-push
run-name: ${{ github.REF_NAME }}
on:
  push:
    branches:
      - RSI-*

jobs:
  main-create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Pull request creation
        if: '!steps.check.outputs.skip'
        run: |
          prs=$(gh pr list \
             --repo "$GITHUB_REPOSITORY" \
             --json baseRefName,headRefName \
             --jq '
                 map(select(.baseRefName == "${{ github.base_ref }}" and .headRefName == "${{ github.REF_NAME }}"))
                 | length
             ')
          if ((prs > 0)); then
            gh pr create \
              -B main \
              -H ${{ github.REF }} \
              --title 'RELEASE OF ${{ github.REF }}' \
              --body 'Created by Github action'
          fi
          

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}