name: master-actions
run-name: RELEASE
on:
  push:
#  pull_request_target:
    branches:
      - RSI-*
jobs:
  change-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Updating tag
        run: |
          latestRelease=$(gh release list \
          -R https://github.com/Red-Sock/rscli \
          --exclude-drafts \
          --exclude-pre-releases \
          -L 1)
          IFS='	'
          read -a latestReleaseArr <<< "$latestRelease"
          
          echo "Latest release is $latestReleaseArr[0]"
        env:
          GH_TOKEN: ${{ github.token }}

