name: master-actions
run-name: RELEASE
on:
  push:
#  pull_request_target:
    branches:
      - main
      - *
jobs:
  change-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Updating tag
        run: |
          latestRelease=$(gh release list \
          -R https://github.com/Red-Sock/rscli \
          --exclude-drafts \
          --exclude-pre-releases \
          -L 1)
          echo "$latestRelease"


