name: master-actions
run-name: RELEASE
on:
  # change to pull_request_target
  pull_request:
    branches:
      - main
jobs:
  change-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - run: echo 42
      - run: echo $GITHUB_REF
