name: pre-master-actions
run-name: pre-master-checks
on:
  pull_request:
    branches:
      - master

env:
  PATTERN_MK_FILE_PTH: plugins/project/projpatterns/pattern/rscli.mk
  
jobs:

  project-plugin-compiled:
    runs-on: ${{ vars.UBUNTU_IMAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Go env
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Compiling pattern
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          make .compile-pattern
          
          diffs=`git diff`
          
          if ((${#diffs} != 0)); then
            ERR_MESSAGE="Recompile project-pattern before merge to master: 
              Run **make .compile-pattern**  
              and **commit** new changes to this branch."
            gh pr comment ${{ github.event.number }} -b  "$ERR_MESSAGE" >> /dev/null
            echo "$ERR_MESSAGE"
            exit 1
          fi
