name: master-actions
run-name: RELEASE
on:
#  pull_request:
  push:
    branches:
      - RSI-*
#      - main

jobs:
  tag-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Obtaining tag
        id: tag
        run: |
          # obtaining latest stable release
          latestRelease=$(gh release list \
            -R https://github.com/Red-Sock/rscli \
            --exclude-drafts \
            --exclude-pre-releases \
            -L 1)
          
          # predefined variable for splitting strings
          IFS='	'
          
          read -a latestReleaseArr <<< "$latestRelease"
          
          echo "latestRelease=$latestReleaseArr" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Validating tag
        run: |
          patternMKfilePth="plugins/project/processor/patterns/pattern/rscli.mk"
          
          tagFromPattern=`head -n 1 $patternMKfilePth`
          echo "Latest release ${{ steps.tag.outputs.latestRelease }}"
          echo "Release in $patternMKfilePth is $tagFromPattern"